#!/usr/bin/env bash

src_dir="/opt/neovim"

install() {
  if [[ $USER = 'root' ]]; then
    local RELEASE
    RELEASE="$(grep -RPho '(?<=\bNAME=").*?(?=")' -R /etc/*-release)"
    case ${RELEASE} in
    "Ubuntu")
      sudo apt purge vim vim-nox vim-tiny --autoremove -y
      sudo apt install python3-{dev,pip,venv} curl build-essential \
        cmake ninja-build gettext unzip software-properties-common \
        git -y --no-install-recommends
      ;;
    "Rocky Linux" | "AlmaLinux")
      sudo dnf remove vim{,-minimal} python3-neovim -yq
      sudo dnf install gcc-c++ make cmake ShellCheck git ninja-build -yq --setopt=install_weak_deps=False
      sudo dnf install python3-{virtualenv,wheel,pip,devel,jedi} --setopt=install_weak_deps=False -y
      ;;
    esac

    rm -f "$(which nvim 2>/dev/null)"

    rm -rf "${src_dir}"
    mkdir -p "${src_dir}"

    git clone https://github.com/neovim/neovim.git "${src_dir}" && {
      cd "${src_dir}"
    } || exit ${LINENO}

    git checkout stable -q

    make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/usr" -j "$(nproc)" || {
      printf '\e[1;31m%s\e[0m\n' "Error on compile"
      exit ${LINENO}
    }
    sudo make install || exit ${LINENO}
    cd - || exit ${LINENO}

    nvim_binary="$(which nvim)"

    make_alternatives() {
      local alternative
      for alternative in vi vim; do
        update-alternatives --install /usr/bin/$alternative $alternative "${nvim_binary}" 100
        update-alternatives --set $alternative "${nvim_binary}"
      done
      update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 1000
    }

    make_alternatives || exit ${LINENO}
  fi

}

if [[ ! -d ${src_dir} ]] || [[ $1 = "force" ]]; then
  install
fi

PYTHON_VERSION='3.11'

vim_conf_dir="${HOME}/.config/nvim"

rm -rf "${vim_conf_dir}"
mkdir -p "${vim_conf_dir}"

vimrc="${vim_conf_dir}/init.vim"

python_bin=$(which python${PYTHON_VERSION}) || exit 222

${python_bin}  -m pip freeze --user | grep -q 'pynvim' || \
  ${python_bin} -m pip install --user pynvim --upgrade --no-cache-dir 2>/dev/null

cp "$(dirname "$(realpath "$0")")/neovim_misc/init.vim" "${vimrc}" || exit ${LINENO}

awk -i inplace -v pb="${python_bin}" '{ gsub(/->python-bin<-/, pb) ; print }' "${vimrc}"

curl -sfL https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
  -o "${vim_conf_dir}"/autoload/plug.vim --create-dirs

nvim +PlugInstall +qall

sed -ri '/neomake|airline|netrw|colorscheme|lastplace|gitgutter/s/^"//' "${vimrc}"
